# The language here really is shell. There is an unused (in CI) setup.py
# but that does not command a hassle of requiring a python version that
# exists on all Travis OSes.
#language: python
# Note: Per travis docs, this is currently alias to language:minimal :
language: shell

sudo: false

# Effectively the list below is for Linux; MacOS is kept separately
os:
  - linux

addons:
  apt:
    packages:
      - bash
      - dash
      - zsh
      - ash
      - busybox
### Currently the syntax of ksh needs too many syntax adaptations vs other shells
###      - ksh

env:
#  global:
#    - DEBUG=99
#    - TEST_PATTERN='test/*.sh'
  matrix:
    - SHELL_PROGS=bash
    - SHELL_PROGS=ash
    - SHELL_PROGS=zsh
    - SHELL_PROGS=dash
    - SHELL_PROGS=busybox
### Currently the syntax of ksh needs too many syntax adaptations vs other shells
#    - SHELL_PROGS=ksh
#    - SHELL_PROGS=ksh88
#    - SHELL_PROGS=ksh93

# Note that this does not inherit env: nor addons:apt:packages from above
matrix:
  include:
  - os: macos
    env: SHELL_PROGS=bash
  - os: macos
    env: SHELL_PROGS=dash
### ZSH test fails probably because of macos awk, needs someone with macos to pick a fix:
### +/usr/bin/awk $'{\n    while ($0) {\n      start=match($0, pattern);\n      token=substr($0, start, RLENGTH);\n      print token;\n      $0=substr($0, start+RLENGTH);\n    }\n  }' 'pattern=("([^[:cntrl:]"\\\\]|[[:blank:]])*((\\\\[^u[:cntrl:]]|\\u[0-9a-fA-F]{4})([^[:cntrl:]"\\\\]|[[:blank:]])*)*")|[+-]?([.][0-9]+|(0+|[1-9][0-9]*)([.][0-9]*)?)([eE][+-]?[0-9]*)?|null|false|true|[[:space:]]+|.'
### +/usr/bin/egrep -v '^[[:space:]]+$'
### +print_debug 2 'parse(1):' 'token='\''"hello\u20world"'\'
#  - os: macos
#    env: SHELL_PROGS=zsh
### Currently the syntax of ksh needs too many syntax adaptations vs other shells
#  - os: macos
#    env: SHELL_PROGS=ksh
  allow_failures:
  - env: SHELL_PROGS=zsh
  - env: SHELL_PROGS=busybox
#  - env: SHELL_PROGS=ksh
#  - env: SHELL_PROGS=ksh88
#  - env: SHELL_PROGS=ksh93

# Currently there is no brew for busybox, ash ...
before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install $SHELL_PROGS ; fi

#- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install bash ; fi
#- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install dash ; fi
#- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install zsh ; fi
#- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install ksh ; fi
#- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install busybox ; fi || echo "FAILED to install optional shell on MacOS"
#- if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install ash ; fi || echo "FAILED to install optional shell on MacOS"

# Whatever the current shebang, replace with hardcoded shell
#script: >
#  sed -i '1s@.*@#!/usr/bin/env bash@' JSON.sh && make check &&
#  sed -i '1s@.*@#!/usr/bin/env zsh@'  JSON.sh && make check &&
#  sed -i '1s@.*@#!/usr/bin/env dash@' JSON.sh && make check

# This version of the script can use specified shell to source and test JSON.sh
# Note that some platforms can lack some interpreters, so a test run
# is effectively skipped and the test looks green if that's the case
script: make check
